### ISSUE TITLE
Training icdar 2017

### ISSUE THREAD

**Issue by ghost** [opconty/keras_std_plus_plus#2]
@opconty 

How to train on icdar 2017?
I have noticed that you std++ code has it's own reconstructed annotations, so how can I prepare the icdar annotations and convert `x1,y1,x2,y2,x3,y3` to std++ annotations?

**Comment by opconty** [comment]
Hi:
a paper will released soon, and we will depict reconstruct the std++ style annotations in detail.
thanks for your attention.

**Comment by ghost** [comment]
@opconty any updates? 
also have you tested on [icdar](https://rrc.cvc.uab.es)

**Comment by opconty** [comment]
sorry for late reply.
plz refer to [this article](https://zhuanlan.zhihu.com/p/78986851).

**Comment by ghost** [comment]
@opconty what about the results it achieves on icdar2015 and icdar2017?
Also, documentation on how to prepare the training data and train and predict...

**Comment by opconty** [comment]
@deepseek 
I have not tested STD ++ on IC15 and IC17, and this is what I have to do.
Also, if you are interested, welcome to join.
