### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by chizhanyuefeng** [opconty/keras_std_plus_plus#3]
hi, it is has paper?

**Comment by yy9568** [comment]
@opconty where is the paper link? Thanks

**Comment by opconty** [comment]
Hi @zhouyuangan @zhouyuangan 

Thanks for your attention, I do not release a paper, there is a  technique article on zhihu
[STD++](https://zhuanlan.zhihu.com/p/78986851)

Hope this helpful.

**Comment by yy9568** [comment]
@opconty Thanks for your quick reply. I will try your repo on my own datasets, it's a good job you did I believe after reading your blog, thank you again. I will follow you on zhihu.com, I look forward to seeing your more excellent works.

**Comment by opconty** [comment]
@zhouyuangan
 thanks, I'll keep on trying
