### ISSUE TITLE
Inference Speed

### ISSUE THREAD

**Issue by yy9568** [opconty/keras_std_plus_plus#5]
@opconty  As the title says, could you provide inference speed for me? I trained model on the mtwi dataset and ran predict.py to visualize result but cost 5 seconds per image, it's weird and confusing.

**Comment by deepseek** [comment]
@opconty

**Comment by ghost** [comment]
@zhouyuangan @opconty 

- Which version of tensorflow are you using?
- What changes did you make to `config.py` and `train.py` in-order to train the `mtwi` dataset?
- For training `mtwi` dataset, what is your folder structure?
- upload your trained model so i can test.

**Comment by opconty** [comment]
@zhouyuangan 
HI，
sorry for late reply, so busy these days.
and I tested the speed is 21fps on my GTX 1080, besides, it depends on many factors.
hope this helpful and keep trying.

**Comment by yy9568** [comment]
@deepseek 
Question1
My tensorflow version is 1.12.0.
Question2
I didn't make training on the mtwi dataset at all.
That's all.

**Comment by yy9568** [comment]
@opconty Thank you very much. Some of my pictures are dense texts which more than 100 text instances, so I tested it and got 1~2 FPS.

**Comment by yy9568** [comment]
@deepseek Please create a new issue about Dataset Structure, so I need to close this issue, thank you.
