### ISSUE TITLE
Generate XML annotations on own dataset

### ISSUE THREAD

**Issue by yy9568** [opconty/keras_std_plus_plus#6]
@opconty I have a dataset contains some gt files formated like x1,y1,x2,y2,...,x4,y4, label, I inspect your provided xml and confused me, could you provide script or code block for me? Thanks a lot.

**Comment by yy9568** [comment]
![29920248](https://user-images.githubusercontent.com/18241276/72491092-f6116e80-3853-11ea-9df5-53536b3e6656.jpg)
I wrote the python script for generating std++ style format dataset on my dataset, I had trained std++, that's my test result above. Some single words are rotated seem that angle is not regressed well, but the other text lines performed well enough as psenet,  you did a great job! But I still will watch your future work on how to generate a specific std++ style format dataset, I doubt that my code is not precise. I had implemented a quadrangle detection based on yolo, the same problem that a single word has no precise orientation like the above picture shows. Could you give me some advances in training std++? Maybe my dataset-generated script is not good, looking forward to seeing your next step. Thanks.

**Comment by yy9568** [comment]
@opconty

**Comment by opconty** [comment]
HI, sorry for late reply.
std++ style format annotation can be generated from original text box  by splitting it into mini-square boxes.

![how to generate miniboxes](https://pic1.zhimg.com/80/v2-171e652bff549378ec7826713295ff5c_hd.jpg)

**Comment by yy9568** [comment]
@opconty Thank you! I think that my code works well, the model trained well,  I got the good result as I showed in vehicle certification.
